[package]
name = "rbit"
version = "0.0.1"
authors = ["stsh"]
edition = "2018"

[dependencies]
bencoder = { path = "../bencoder" }
requester = { path = "../requester" }
percent-encoding = "*"
rust-crypto = "*"
